function ncsAlign(behDir,subj,ncsID,sampRate,threshMS,window,ms_field)
% ncsAlign - uses pulses generated by neuralynx_split.m and stored in the
% ncsID.sync.txt and aligns thses pulses with the pulses stored in the
% eeglog file in the behavioral directory (behDir).  this function performs
% the same things as alignTool for the clinical system, but tailored to the
% neuralynx setup and without a gui
% 
% FUNCTION:
%   ncsAlign(behDir,subj,ncsID,sampRate)
%
% INPUT ARGS:
%   behDir:            % This is the directory where the behavioral files
%                           are located including eeglog and eventsNcs.mat
%   subj:              % This is the name of the subject folder
%   ncsID;             % Name of the NCS files that are created using
%                           neuralynx_split (ncsID.sync.txt and ncsID.001)
%   sampRate = 2000;   % Samplerate of the eeg data
%   threshMS = 10;     % The threshold for matching (bigger is
%                      %  weaker criterion)
%   window = 100;      % The number of events to match at the
%                      %   % beginning and end
%   ms_field='mstime'; % Default ms_field name
%
%
%
% behDir = '/data/eeg/UP011/behavioral/catFR/UP011/session_1';
% subj = 'UP011';
% ncsID = 'UP011_16Jul07_1501';
%


if ~exist('sampRate','var')
  sampRate = 2000;
end
if ~exist('threshMS','var')
  threshMS = 10;
end
if ~exist('window','var')
  window = 100;
end
if ~exist('ms_field','var')
  ms_field = 'mstime';
end

% create directories and filenames
behFile=fullfile(behDir, 'eeg.eeglog.up');
pulseFile=fullfile('/data/eeg',subj,'eeg.noreref.neuralynx',[ncsID '.sync.txt']);
% chanFile=fullfile('/data/eeg',subj,'eeg.noreref.neuralynx',[ncsID '.001']);
% Change this to read eeg data off of rereferenced eeg files
chanFile=fullfile('/data/eeg',subj,'eeg.reref.neuralynx',[ncsID '.001']);
logFile=fullfile(behDir,'eventsNcs.mat');


% load in the beh_ms as determined in eeg.eeglog.up file
beh_ms = textread(behFile,'%n%*[^\n]','delimiter','\t');

% sort it
beh_ms = sort(beh_ms);

% Get pulses
pulses=textread(pulseFile,'%n\n');
pulse_ms = pulses*1000/sampRate;

% Remove all pulses under 100ms (Part of Start and End pulses)
dp = diff(pulse_ms);
yp = find(dp < 100);
pulse_ms(yp+1) = [];
pulses(yp+1) = [];

% Run pulsealign
mywin = min(round(length(pulses)/2),window);
if mywin < 5
  mywin = 5;
end
  
[beh_in,eeg_in] = pulsealign(beh_ms,pulses,sampRate,threshMS,mywin);


% Run logalign, which aligns the data based on one eeg file and rewrite
% events structure - this version of logalign takes in cell arrays as arguments

logalign({beh_in},{eeg_in},{chanFile},{logFile},ms_field);

